spring:
  profiles:
    active: ${ACTIVE_PROFILE}

  datasource:

    url: jdbc:sqlserver://10.16.167.113;databaseName=GBMS;sendStringParametersAsUnicode=false;encrypt=true;trustServerCertificate=true;
    username: prx_gbms_appl
    password: ZL4oT}M<gL8hRy>e
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      poolName: HikariCP
      minimumIdle: 10
      maximumPoolSize: 100
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  cloud:
    gcp:
      common:
        project-id: ${COMMON_PROJECT_ID}
        project-number: ${COMMON_PROJECT_NUMBER}
      psa:
        project-id: ${PSA_PROJECT_ID}
        project-number: ${PSA_PROJECT_NUMBER}
      sql:
        database-name: gbms
        enable-iam-auth: true
        enabled: true
        instance-connection-name: ${instanceName}
        ip-types: PRIVATE
  main:
    allow-bean-definition-overriding: true # required
  batch:
    jdbc:
      initialize-schema: always

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  paths-to-match: /api/**
  swagger-ui:
    enabled: true
    path: /swagger-ui

# Swagger
swagger:
  title: GBMS Manage GPC Service
  description: This service is used to manage GPC functionality
  contactName: rgavinol
  contactEmail: rgavinol@ford.com
  licenseName: Ford License
  version: '@gradle.properties.version@'
  serverUrl: ${serviceBaseUrl}
  tokenUrl: https://login.microsoftonline.com/azureford.onmicrosoft.com/oauth2/v2.0/token
  scope: ${scope}

instanceName: ${PSA_PROJECT_ID}:us-central1:gbms-pgsql-db
serviceBaseUrl: https://api.d01i.gcp.ford.com/pro/govdeals/managegpc

####################################################################################################
# !!! IMPORTANT !!! This section changes per environment, see prod configuration in comments.
####################################################################################################
iamAuthBaseUrl: https://api.stg01e.gcp.ford.com/pro/auth # PROD: https://api.pd01e.gcp.ford.com/pro/auth
iamRolesBaseUrl: https://api.stg01e.gcp.ford.com/pro/roles # PROD: https://api.pd01e.gcp.ford.com/pro/roles
ffmIssuer: https://fleetaccount-stage.ford.com # PROD: https://FleetAccount.ford.com/account-api
iam-application-id: c7510d39-eb30-4a58-ac47-bc354ab559a1
scope: 4bb0c26d-6ca5-42bb-b7da-388700170f53/.default
 

# add the following to enable logging
logging:
  level:
    com.ford.pro.auth: DEBUG
ford-pro:
  auth:
    inject-filter: true # this injects a basic SecurityFilterChain that will secure all requests
    unsecured-urls: '/api-docs/**,/swagger-ui/**'
    token:
      authorization:
        roleResolverUrl: ${iamRolesBaseUrl}/v2/resolve-role
      validation:
        issuers:
          - ${ffmIssuer}
        configUrl:
          - ${iamAuthBaseUrl}/v1/.well-known/openid-configuration
        applicationIds:
          #- <insert your application id here>
          - c7510d39-eb30-4a58-ac47-bc354ab559a1
          - 36a9670a-60c6-430f-8a8d-d2c809bedcac
          - 566c19b3-7b9c-4e1d-be13-0cd01eb18b95 # internal admin application id
          - dfc7bb0a-649d-4873-9368-00aef0e7024d # external admin application id
          - c9dec19f-4530-41c0-a477-4524c5c10a97 # ford pro application id
          - 805746a3-51da-40e9-9f93-dd7db89bdb8c
      extraction: # 'extraction.access-token-header' tells the interceptor where to look for the token.
        access-token-header: x-forwarded-authorization # we expect the token to be in the 'x-forwarded-authorization' header
    user-detail:
      cache-time-in-minutes: 5
      cache-size: 100

###################################################################################
  # CORS headers to support accessing APIs from web browsers
###################################################################################
cn:
  app:
    filters:
      cors-filter:
        enabled: true
        allowed-origins: [https://localhost:3009,https:/api.dev.fordpro.com/fpg-bff,https:/api.stage.fordpro.com/fpg-bff,https:/api.fordpro.com/fpg-bff,https:/dev.fordpro.com,https:/stage.fordpro.com,https:/fordpro.com]https://localhost:3009,https://api.dev.fordpro.com/fpg-bff,https://api.stage.fordpro.com/fpg-bff,https://api.fordpro.com/fpg-bff,https://dev.fordpro.com,https://stage.fordpro.com,https://fordpro.com
        allowed-headers: accept,authorization,content-type,user-agent,x-csrftoken,x-requested-with
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-path-pattern: /api/**
        allow-credentials: true

 