spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:gbms;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      poolName: HikariCP
      schema: PUBLIC
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: false
        globally_quoted_identifiers: false
        default_schema: PUBLIC
        format_sql: true
    show-sql: true

serviceBaseUrl: ${serviceBaseUrl}
iam-application-id: c7510d39-eb30-4a58-ac47-bc354ab559a1
scope: ${scope}

COMMON_PROJECT_ID: PROJECT_ID
COMMON_PROJECT_NUMBER: PROJECT_NUMBER
PSA_PROJECT_ID: PRA_PROJECT_ID
PSA_PROJECT_NUMBER: PRA_PROJECT_NUMBER